name: Empfehlung 채ndern
description: Bestehende Empfehlung per ID 채ndern
labels: [reco-edit]
body:
  - type: input
    id: id
    attributes:
      label: Datensatz-ID
      description: In investitionsdetails/data/recommendations.json zu finden
    validations:
      required: true
  - type: input
    id: symbol
    attributes:
      label: Symbol (optional)
  - type: input
    id: name
    attributes:
      label: Name (optional)
  - type: dropdown
    id: plan
    attributes:
      label: Typ (optional)
      options: [Kostenlos, Kostenpflichtig]
  - type: input
    id: recPrice
    attributes:
      label: Empfehlungspreis (optional)
  - type: input
    id: recDate
    attributes:
      label: Empfehlungsdatum (optional)
  - type: dropdown
    id: horizon
    attributes:
      label: Zielhorizont (optional)
      options: [Kurzfristig, Langfristig]
  - type: dropdown
    id: status
    attributes:
      label: Status (optional)
      options: [open, sold]
  - type: dropdown
    id: manager
    attributes:
      label: Manager best채tigt Verkauf (optional)
      options: [Nein, Ja]
  - type: input
    id: soldPrice
    attributes:
      label: Verkaufspreis (optional)
  - type: input
    id: soldDate
    attributes:
      label: Verkaufsdatum (optional)
  - type: textarea
    id: reason
    attributes:
      label: Begr체ndung (optional)
      render: text
