name: Import (JSON)
description: Mehrere Einträge per JSON importieren
labels: [reco-import]
body:
  - type: textarea
    id: payload
    attributes:
      label: JSON-Array
      description: Format: [ {...}, {...} ], Felder wie in investitionsdetails/data/recommendations.json (plan: 'paid'|'free')
      render: json
    validations:
      required: true
  - type: dropdown
    id: mode
    attributes:
      label: Modus
      options: [merge, replace]
      description: merge = nach ID zusammenführen, replace = alles ersetzen
      default: 0
