name: Neue Empfehlung
description: Neuen Datensatz für Investitionsdetails anlegen
labels:
  - reco-new
body:
  - type: input
    id: symbol
    attributes:
      label: Symbol
      placeholder: "SAP.DE"
    validations:
      required: true

  - type: input
    id: wkn
    attributes:
      label: WKN (optional)
      placeholder: "716460"

  - type: input
    id: name
    attributes:
      label: Name
      placeholder: "SAP"

  - type: dropdown
    id: plan
    attributes:
      label: Typ
      options:
        - Kostenlos
        - Kostenpflichtig

  - type: input
    id: recPrice
    attributes:
      label: Empfehlungspreis
      description: "Bitte als Zahl, z.B. 185.2 oder 185,2"
      placeholder: "185.2"

  - type: input
    id: recDate
    attributes:
      label: Empfehlungsdatum
      description: "Format: YYYY-MM-DD"
      placeholder: "2025-08-15"

  - type: dropdown
    id: horizon
    attributes:
      label: Zielhorizont
      options:
        - Kurzfristig
        - Langfristig

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - open
        - sold

  - type: dropdown
    id: manager
    attributes:
      label: Manager bestätigt Verkauf
      options:
        - Nein
        - Ja

  - type: input
    id: soldPrice
    attributes:
      label: Verkaufspreis (optional)
      placeholder: "51.80"

  - type: input
    id: soldDate
    attributes:
      label: Verkaufsdatum (optional)
      description: "Format: YYYY-MM-DD"
      placeholder: "2025-08-14"

  - type: textarea
    id: reason
    attributes:
      label: Begründung (kundenseitig sichtbar)
