name: Investitionsdetails Sync (Issues → JSON)

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  issues: write

jobs:
  sync:
    # 只在带 reco- 前缀标签的 Issue 上运行（reco-new / reco-edit / reco-import）
    if: contains(join(fromJson(toJson(github.event.issue.labels))[*].name, ','), 'reco-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Handle issue -> update JSON
        run: node backend/handle-issue.mjs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(investitionsdetails): sync from issue #${{ github.event.issue.number }}"
          file_pattern: |
            investitionsdetails/data/recommendations.json
            backend/.result.md

      - name: Comment & Close
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let summary='(no summary)';
            try { summary = fs.readFileSync('backend/.result.md','utf8'); } catch {}
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: summary
            });
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
